services:
  - type: web
    name: sol-proxy
    env: go
    region: oregon
    plan: free
    rootDir: relay-backend
    buildCommand: go mod tidy && go build -o sol-relay
    startCommand: ./sol-relay
    envVars:
      - key: PORT
        value: 8080
