services:
  - type: web
    name: sol-proxy
    env: go
    region: oregon
    plan: free
    buildCommand: cd relay-backend && go build -o sol-relay
    startCommand: ./sol-relay
    envVars:
      - key: PORT
        value: 8080
